-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 19:19:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema consolestock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consolestock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consolestock` DEFAULT CHARACTER SET utf8mb4 ;
USE `consolestock` ;

-- -----------------------------------------------------
-- Table `consolestock`.`console_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consolestock`.`console_brands` ;

CREATE TABLE IF NOT EXISTS `consolestock`.`console_brands` (
  `console_brand_id` INT NOT NULL AUTO_INCREMENT,
  `console_brand_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`console_brand_id`),
  UNIQUE INDEX `brand_name_UNIQUE` (`console_brand_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consolestock`.`console_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consolestock`.`console_types` ;

CREATE TABLE IF NOT EXISTS `consolestock`.`console_types` (
  `console_type_id` INT NOT NULL AUTO_INCREMENT,
  `console_type_name` VARCHAR(60) NOT NULL,
  `console_brand_id` INT NOT NULL,
  `console_type_release` DATE NOT NULL,
  PRIMARY KEY (`console_type_id`),
  UNIQUE INDEX `console_type_name_UNIQUE` (`console_type_name` ASC) VISIBLE,
  INDEX `console_type_brand_link_idx` (`console_brand_id` ASC) INVISIBLE,
  INDEX `console_type_release_idx` (`console_type_release` ASC) VISIBLE,
  CONSTRAINT `console_type_brand_link`
    FOREIGN KEY (`console_brand_id`)
    REFERENCES `consolestock`.`console_brands` (`console_brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consolestock`.`console_sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consolestock`.`console_sellers` ;

CREATE TABLE IF NOT EXISTS `consolestock`.`console_sellers` (
  `console_seller_id` INT NOT NULL AUTO_INCREMENT,
  `console_seller_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`console_seller_id`),
  UNIQUE INDEX `seller_name_UNIQUE` (`console_seller_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consolestock`.`console_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consolestock`.`console_conditions` ;

CREATE TABLE IF NOT EXISTS `consolestock`.`console_conditions` (
  `console_condition_id` INT NOT NULL AUTO_INCREMENT,
  `console_condition_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`console_condition_id`),
  UNIQUE INDEX `console_condition_name_UNIQUE` (`console_condition_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consolestock`.`console_listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consolestock`.`console_listings` ;

CREATE TABLE IF NOT EXISTS `consolestock`.`console_listings` (
  `console_listing_id` INT NOT NULL AUTO_INCREMENT,
  `console_type_id` INT NOT NULL,
  `console_condition_id` INT NOT NULL,
  `console_seller_id` INT NOT NULL,
  `console_listing_url` VARCHAR(500) NOT NULL,
  `console_listing_active` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `console_listing_date` DATE NOT NULL,
  `console_listing_price` FLOAT UNSIGNED,
  PRIMARY KEY (`console_listing_id`),
  INDEX `console_listing_url_UNIQUE` (`console_listing_url` ASC) VISIBLE,
  INDEX `console_listing_type_link_idx` (`console_type_id` ASC) VISIBLE,
  INDEX `console_listing_condition_link_idx` (`console_condition_id` ASC) VISIBLE,
  INDEX `console_listing_seller_link_idx` (`console_seller_id` ASC) VISIBLE,
  INDEX `console_listing_date_idx` (`console_listing_date` ASC) INVISIBLE,
  INDEX `console_listing_active_idx` (`console_listing_active` ASC) VISIBLE,
  INDEX `console_listing_price_idx` (`console_type_id` ASC, `console_listing_price` ASC) VISIBLE,
  CONSTRAINT `console_listing_type_link`
    FOREIGN KEY (`console_type_id`)
    REFERENCES `consolestock`.`console_types` (`console_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `console_listing_condition_link`
    FOREIGN KEY (`console_condition_id`)
    REFERENCES `consolestock`.`console_conditions` (`console_condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `console_listing_seller_link`
    FOREIGN KEY (`console_seller_id`)
    REFERENCES `consolestock`.`console_sellers` (`console_seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;